AWSTemplateFormatVersion: '2010-09-09'
Description: 'app

  Sample SAM Template for app

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  ProcessFormFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ProcessFormFunction
      - Arn
  ProcessFormFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - ProcessFormFunctionRole
      - Arn
  ShowFormFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ShowFormFunction
      - Arn
  ShowFormFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - ShowFormFunctionRole
      - Arn
  UploadBucket:
    Description: S3 Bucket Information
    Value:
      Ref: UploadS3Bucket
  UserFormApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/
Parameters:
  AppStage:
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 1- 10 latin letters
    Default: api
    Description: Prefixo do endpoint
    MaxLength: 10
    MinLength: 1
    Type: String
Resources:
  ErrorFunction:
    Properties:
      AutoPublishAlias: pegue
      CodeUri: s3://mathgraca-lambda-test/54b694c1945f0049907b63e43a53d837
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /error
          Type: Api
      Handler: app.lambdaError
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  HelloWorldError:
    Properties:
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: ShowFormFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 5
      TreatMissingData: notBreaching
    Type: AWS::CloudWatch::Alarm
  ProcessFormFunction:
    Properties:
      CodeUri: s3://mathgraca-lambda-test/e56464937b6d4edebb728b27abf2925d
      Environment:
        Variables:
          UPLOAD_S3_BUCKET:
            Ref: UploadS3Bucket
      Events:
        SubmitForm:
          Properties:
            Method: post
            Path: /
            RestApiId:
              Ref: WebApi
          Type: Api
      Handler: process-form.lambdaHandler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  ShowFormFunction:
    Properties:
      AutoPublishAlias: pegue
      CodeUri: s3://mathgraca-lambda-test/85c4f500103aa172596c3f467fab496e
      Events:
        ShowForm:
          Properties:
            Method: get
            Path: /
            RestApiId:
              Ref: WebApi
          Type: Api
      Handler: show-form.lambdaHandler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  UploadS3Bucket:
    Type: AWS::S3::Bucket
  WebApi:
    Properties:
      StageName:
        Ref: AppStage
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
