AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Convert file in S3
Globals:
  Function:
    Timeout: 3
Parameters:
  AppStage:
    Type: String
    Default: api
    Description: Prefixo do endpoint
    AllowedPattern: ^[A-Za-z]+$
    MaxLength: 10
    MinLength: 1
    ConstraintDescription: 1- 10 latin letters
  UploadLimitInMb:
    Type: Number
    Default: 5
    Description: Maximum upload size in megabytes
    MinValue: 1
    MaxValue: 100
  ThumbnailWidth:
    Type: Number
    Default: 300
    Description: Thumbnail width in pixels
    MinValue: 10
    MaxValue: 1000
  AllowedImageExtensions:
    Type: String
    Default: jpg,jpeg,png,gif
    Description: Comma-delimited list of allowed image file extensions (lowercase)
Resources:
  ImageMagick:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:145266761615:applications/image-magick-lambda-layer
        SemanticVersion: 1.0.0
  WebAssetsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
  UploadS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - POST
          AllowedOrigins:
          - Fn::GetAtt:
            - WebAssetsS3Bucket
            - WebsiteURL
          MaxAge: 3600
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: AppStage
      Cors:
        Fn::Sub: '''${WebAssetsS3Bucket.WebsiteURL}'''
  ThumbnailsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          AllowedOrigins:
          - Fn::GetAtt:
            - WebAssetsS3Bucket
            - WebsiteURL
          MaxAge: 3600
  ConvertFunctionCanReadUploads:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ConvertFunctionCanReadUploads
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - Fn::Sub: ${UploadS3Bucket.Arn}/*
      Roles:
      - Ref: ConvertFileFunctionRole
  ShowFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mathgraca-lambda-test/1d53b8076436edb99fc9a4c3ba281fe1
      Handler: show-form.lambdaHandler
      Runtime: nodejs10.x
      Events:
        ShowForm:
          Type: Api
          Properties:
            Path: /sign/{extension}
            Method: get
            RestApiId:
              Ref: WebApi
      Environment:
        Variables:
          UPLOAD_S3_BUCKET:
            Ref: UploadS3Bucket
          UPLOAD_LIMIT_IN_MB:
            Ref: UploadLimitInMb
          CORS_ORIGIN:
            Fn::GetAtt:
            - WebAssetsS3Bucket
            - WebsiteURL
          THUMBNAILS_S3_BUCKET:
            Ref: ThumbnailsS3Bucket
          ALLOWED_IMAGE_EXTENSIONS:
            Ref: AllowedImageExtensions
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: UploadS3Bucket
      - S3ReadPolicy:
          BucketName:
            Ref: ThumbnailsS3Bucket
  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mathgraca-lambda-test/1885824c75584bc6f79b773eaea00d7f
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        FileUploaded:
          Type: S3
          Properties:
            Bucket:
              Ref: UploadS3Bucket
            Events: s3:ObjectCreated:*
      Timeout: 600
      MemorySize: 1024
      Environment:
        Variables:
          OUTPUT_BUCKET:
            Ref: ThumbnailsS3Bucket
          THUMB_WIDTH:
            Ref: ThumbnailWidth
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: ThumbnailsS3Bucket
      Layers:
      - Fn::GetAtt:
        - ImageMagick
        - Outputs.LayerVersion
  DeployToS3:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/deploy-to-s3
        SemanticVersion: 1.0.0
  SiteSource:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
      - Fn::GetAtt:
        - DeployToS3
        - Outputs.Arn
      CodeUri: s3://mathgraca-lambda-test/7f8d31924c781581499c7f59a238cbe2
      AutoPublishAlias: production
      Runtime: python3.7
      Handler: deployer.resource_handler
      Timeout: 600
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: WebAssetsS3Bucket
  DeploymentResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - SiteSource
        - Arn
      Version:
        Ref: SiteSource.Version
      TargetBucket:
        Ref: WebAssetsS3Bucket
      Substitutions:
        FilePattern: '*.html'
        Values:
          API_URL:
            Fn::Sub: https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/
      Acl: public-read
      CacheControlMaxAge: 600
Outputs:
  UserFormApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/
  UploadBucket:
    Description: S3 Bucket Information
    Value:
      Ref: UploadS3Bucket
  WebUrl:
    Description: Public web URL
    Value:
      Fn::GetAtt:
      - WebAssetsS3Bucket
      - WebsiteURL
Metadata:
  AWS::ServerlessRepo::Application:
    Name: image-thumbnails
    Description: 'A sample application for the Running Serverless book tutorial

      '
    Author: Matheus Graca
    SemanticVersion: 1.0.0
    SpdxLicenseId: MIT
    LicenseUrl: s3://mathgraca-lambda-test/9cc28cd3806a78f8f5fb1e435ee958d3
    ReadmeUrl: s3://mathgraca-lambda-test/5b08520ea73f1d77829b486480b0b946
    Labels:
    - layer
    - image
    - lambda
    - imagemagick
