AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app

  Sample SAM Template for app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AppStage:
    Type: String
    Default: api
    Description: Prefixo do endpoint 
    AllowedPattern: ^[A-Za-z]+$
    MaxLength: 10
    MinLength: 1
    ConstraintDescription: "1- 10 latin letters"

Resources:
  UploadS3Bucket:
    Type: AWS::S3::Bucket

  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppStage

  ShowFormFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user-form/
      Handler: show-form.lambdaHandler
      Runtime: nodejs10.x
      AutoPublishAlias: pegue
     # DeploymentPreference:
     #   Type: Linear10PercentEvery1Minute
     #    Alarms:
     #     - !Ref HelloWorldError
      Events:
        ShowForm:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref WebApi

  ProcessFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user-form/
      Handler: process-form.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          UPLOAD_S3_BUCKET: !Ref UploadS3Bucket
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref UploadS3Bucket
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref WebApi

  HelloWorldError:
    Type: AWS::CloudWatch::Alarm 
    Properties:
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 5
      Period: 60
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Namespace: "AWS/Lambda"
      Dimensions:
        - Name: FunctionName
          Value: !Ref ShowFormFunction
  ErrorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user-form/
      Handler: app.lambdaError
      Runtime: nodejs10.x
      AutoPublishAlias: pegue
      # DeploymentPreference:
      #  Type: Linear10PercentEvery1Minute
      #  Alarms:
      #    - !Ref HelloWorldError
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /error
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserFormApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"
  UploadBucket:
    Description: "S3 Bucket Information"
    Value: !Ref UploadS3Bucket
  ShowFormFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShowFormFunction.Arn
  ShowFormFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShowFormFunctionRole.Arn
  ProcessFormFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ProcessFormFunction.Arn
  ProcessFormFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ProcessFormFunctionRole.Arn
